/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;



import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean search(ArrayList<Integer>array,int e)
    {
       System.out.println("dizide var");
       if(array==null) return false;
       for(int elt:array){
           if(elt==e) return true;
       } 
       return false;

    }
}