/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;


import org.junit.jupiter.api.Test;

import static java.util.Arrays.asList;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
   public void testFound(){
       int array[]={1,2,3,4,5,6,7};
       assertTrue(App.ciftSayibulma(array, 3));
   }
    

    @Test
    public void testNotFound(){
        int array [] = {1,2,3,4,5,6,7};
        assertFalse(App.ciftSayibulma(array,1));
    }

   /*  @Test
    public void testNull(){
        assertFalse(App.ciftSayibulma(null,0));

    }*/
    @Test 
    public void testEmptyArray()
    {
        int array [] = {};
        assertFalse(App.ciftSayibulma(array, 1));
    }
}
