/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;


import org.junit.jupiter.api.Test;

import static java.util.Arrays.asList;
import static odev3.App.search;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testFound(){
        ArrayList<Integer>array=new ArrayList<>(asList(1,2,3,4,5));
        assertTrue(search(array, 4));

    }

    @Test
    public void testNull(){

        assertFalse(search(null,1));

    }
}
